version: 2.1
orbs:
  docker: circleci/docker@2.8.2

workflows:
  node-js-sample-workflow:
    jobs:
      - docker/publish:
          image: node-js-sample
          tag: latest
          deploy: true
          docker-username: $DOCKER_LOGIN
          docker-password: $DOCKER_PASSWORD
